"use client";

import React, { useState, useEffect, useRef } from "react";

function getRandomNumber(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export default function Home() {
  // constants:
  const testTexts = [
    `In the early 19th century, the Industrial Revolution transformed economies from agrarian-based to industrial. Factories sprang up in cities, bringing an influx of workers from rural areas. With the rise of machinery, production shifted from handmade to machine-made goods, leading to faster output and lower prices. The shift significantly improved living standards for many, although it also brought challenges such as crowded urban living conditions and long working hours. Despite these issues, the Industrial Revolution marked a turning point in human history, leading to technological innovations that paved the way for modern society.`,

    `The Amazon Rainforest, often called the "lungs of the Earth," is a vast tropical forest that covers much of the Amazon Basin in South America. It plays a crucial role in regulating the global climate by absorbing large amounts of carbon dioxide and releasing oxygen. The forest is home to a staggering diversity of wildlife, including millions of species of insects, birds, and mammals, many of which are not found anywhere else. However, deforestation poses a significant threat to this vital ecosystem. Large areas of the forest are being cleared for agriculture, mining, and logging, endangering both the environment and the species that live there.`,

    `Water is a vital resource for all living organisms, but it is not always easily accessible. Many regions of the world suffer from water scarcity, particularly in arid and semi-arid areas. In these regions, people rely heavily on rainwater harvesting, groundwater extraction, and water recycling to meet their needs. Climate change, population growth, and pollution have exacerbated the water crisis, making it a global issue. Governments and organizations around the world are working to find sustainable solutions, such as desalination, improved irrigation practices, and more efficient water usage in industries.`,

    `The theory of evolution by natural selection, first proposed by Charles Darwin in the 19th century, revolutionized the field of biology. It provided a scientific explanation for the diversity of life on Earth, suggesting that species evolve over time through a process of genetic variation and environmental pressure. According to Darwin's theory, individuals with traits that better suit their environment are more likely to survive and reproduce, passing those advantageous traits to the next generation. This process, known as natural selection, leads to the gradual adaptation of species to their surroundings over many generations.`,

    `Renewable energy sources, such as solar, wind, and hydropower, have become increasingly important in the fight against climate change. Unlike fossil fuels, which emit harmful greenhouse gases when burned, renewable energy sources produce little to no emissions. Solar energy, in particular, has seen rapid advancements in recent years, making it more affordable and accessible to both individuals and businesses. Wind energy, generated by large turbines, has also become a popular choice in many regions. By investing in renewable energy, countries can reduce their carbon footprints and move towards a more sustainable future.`,

    `The human brain is an incredibly complex organ, responsible for controlling all bodily functions and enabling thought, emotion, and memory. It is made up of billions of neurons, which communicate with each other through electrical and chemical signals. The brain is divided into several regions, each with its own specific functions. For example, the frontal lobe is associated with decision-making and problem-solving, while the hippocampus is crucial for memory formation. Despite decades of research, scientists are still uncovering new information about how the brain works and how it can be affected by diseases, injuries, and aging.`,

    `In recent years, social media has become a dominant force in communication, shaping the way people interact with each other and consume information. Platforms such as Facebook, Twitter, and Instagram allow users to share their thoughts, photos, and videos with a global audience. While social media has many benefits, such as connecting people across distances and raising awareness of important issues, it also has downsides. Cyberbullying, misinformation, and the spread of fake news have become major concerns. As social media continues to evolve, society must address these challenges to ensure a positive and safe online environment.`,

    `Globalization refers to the increasing interconnectedness of the world's economies, cultures, and populations. This phenomenon has been driven by advances in communication, transportation, and technology, which have made it easier for people, goods, and ideas to move across borders. While globalization has led to economic growth and the spread of innovation, it has also raised concerns about cultural homogenization and the widening gap between rich and poor. In many countries, local industries have struggled to compete with multinational corporations, leading to job losses and economic inequality. Balancing the benefits and challenges of globalization remains a key issue in today's world.`,

    `Artificial intelligence (AI) is rapidly changing the landscape of many industries, from healthcare to finance to transportation. AI technologies, such as machine learning and natural language processing, enable computers to perform tasks that typically require human intelligence, such as recognizing speech, identifying patterns, and making decisions. In healthcare, AI is being used to develop more accurate diagnostic tools, while in finance, it is helping to detect fraud and manage investments. However, the rise of AI has also raised ethical concerns, particularly regarding job displacement and the potential misuse of AI-powered systems. As AI continues to advance, it will be important to address these challenges responsibly.`,

    `Space exploration has long captured the human imagination, and in recent decades, it has seen remarkable advancements. From the moon landings of the 1960s to the exploration of Mars, humanity has pushed the boundaries of what is possible. The International Space Station (ISS), a collaborative project involving multiple countries, serves as a hub for scientific research in space. Private companies, such as SpaceX, have also entered the space race, working on reusable rockets and plans for future missions to the moon and beyond. While space exploration presents numerous challenges, such as the vast distances and harsh conditions, it continues to inspire a sense of wonder and curiosity about the universe.`,
  ];

  function getTestText(testText: string): string[] {
    const words = testText
      .trim()
      .replaceAll("\n", "")
      .split(/\s+/) // Split by whitespace
      .filter(Boolean); // Remove any empty strings

    return words;
  }

  // states:
  const [testContent, setTestContent] = useState<string[]>(
    getTestText(testTexts[0])
  );
  const [wordsRead, setWordsRead] = useState({
    count: 0,
    time: 0.0,
  });
  const [readingSpeed, setReadingSpeed] = useState(0);
  const [startTime, setStartTime] = useState<number | null>(null);
  const [elapsedTime, setElapsedTime] = useState<number>(0);
  const [isRunning, setIsRunning] = useState<boolean>(false);

  // refs:
  const wordRefs = useRef<(HTMLSpanElement | null)[]>([]);

  // event handler functions:
  const handleWordClick = (index: number) => {
    if (index + 1 === testContent.length) {
      setIsRunning(false);
    }

    if (isRunning) {
      const count = index + 1 - wordsRead.count;
      const time = (elapsedTime - wordsRead.time) / 1000 / 60;
      const speed = count / time;

      if (speed > 700) {
        handleResetBtn();
        alert("😒NO CHEATING!!😒");
      } else if (speed < 0) {
        handleResetBtn();
        alert("🚫No going back!🚫");
      } else {
        setReadingSpeed((prev) => {
          return Number(((prev + speed) / 2).toFixed(1));
        });
      }
    }
    setWordsRead({ count: index + 1, time: elapsedTime });
  };

  const handleResetBtn = () => {
    setReadingSpeed(0);
    setWordsRead({
      count: 0,
      time: 0.0,
    });
    setStartTime(null);
    setElapsedTime(0);
    setIsRunning(false);
    setTestContent(
      getTestText(testTexts[getRandomNumber(0, testTexts.length - 1)])
    );
    window.scrollTo(0, 0);
  };

  const handleStartBtn = () => {
    handleResetBtn();
    setStartTime(Date.now());
    setIsRunning(true);
  };

  // useEffects:
  useEffect(() => {
    let intervalId: NodeJS.Timeout | null = null;

    if (isRunning && startTime !== null) {
      intervalId = setInterval(() => {
        setElapsedTime(Date.now() - startTime);
      }, 100);
    }

    return () => {
      if (intervalId) clearInterval(intervalId);
    };
  }, [isRunning, startTime]);

  useEffect(() => {
    let intervalId2: NodeJS.Timeout | null = null;

    const simulateRandomClick = () => {
      const randomIndex = getRandomNumber(10, testContent.length - 1);
      const randomWordRef = wordRefs.current[randomIndex];

      if (randomWordRef) {
        randomWordRef.classList.add("bg-[#4A3C31bb]");
        setTimeout(() => {
          randomWordRef.classList.remove("bg-[#4A3C31bb]");
        }, 1000);
      }
    };

    if (!isRunning) {
      intervalId2 = setInterval(() => {
        simulateRandomClick();
      }, 1000);
    }

    return () => {
      if (intervalId2) clearInterval(intervalId2);
    };
  }, [isRunning, testContent]);

  return (
    <section className="relative w-screen max-w-[520px] m-auto min-h-screen flex flex-col items-center justify-between">
      <div className="sticky top-0 z-10 bg-[#F4E3C1] w-full p-2 shadow-lg">
        <p className="flex items-center justify-between text-2xl bg-[#4A3C31bb] text-[#FAF3E0] rounded w-full p-3">
          {isRunning || elapsedTime > 0 ? (
            <React.Fragment>
              <span>{(elapsedTime / 1000).toFixed(1)} sec</span>
              <span>{readingSpeed} wpm</span>
            </React.Fragment>
          ) : (
            <span className="w-full text-center text-lg">
              Tap the current word every few seconds;
            </span>
          )}
        </p>
      </div>

      <article
        className={`min-h-screen px-4 py-3 text-justify bg-[#FAF3E0] text-[#4A3C31] text-xl select-none cursor-pointer transition-opacity duration-100 ${
          isRunning ? "opacity-100 blur-none" : "opacity-75 blur-sm"
        }`}
      >
        {testContent.map((word, index) => (
          <React.Fragment key={index}>
            <span
              ref={(ele) => {
                wordRefs.current[index] = ele;
              }}
              onClick={() => handleWordClick(index)}
              className="rounded active:bg-[#4A3C31] active:transition-colors duration-1000"
            >
              {word}
            </span>{" "}
          </React.Fragment>
        ))}
      </article>

      <div className="sticky bottom-0 z-10 bg-[#F4E3C1] w-full flex items-center gap-1 p-1">
        <button
          onClick={() => handleStartBtn()}
          disabled={isRunning}
          className="w-full bg-[#4A3C31] text-[#FAF3E0] px-6 py-2 rounded text-2xl font-bold cursor-pointer active:scale-95 active:bg-[#4A3C31bb] disabled:opacity-50"
        >
          START
        </button>

        <button
          onClick={() => handleResetBtn()}
          className="w-full bg-[#4A3C31] text-[#FAF3E0] px-6 py-2 rounded text-2xl font-bold cursor-pointer active:scale-95 active:bg-[#4A3C31bb]"
        >
          RESET
        </button>
      </div>
    </section>
  );
}
